Feature/fix readme
ERNI-Academy/assets-cloud-storage-abstraction pull request #12
Opened 2022-05-02 09:50 UTC by omaramalfi

# fix readme

2022-05-03 07:17 UTC, Rabosa616 requested changes

2022-05-03 07:17 UTC, Rabosa616 commented on CONTRIBUTING.md
> +[code_of_conduct]: https://github.com/rgonzalezabreu/masterpiece/blob/main/CODE_OF_CONDUCT.md
Why this change?

2022-05-03 07:23 UTC, omaramalfi commented on CONTRIBUTING.md
> +[code_of_conduct]: https://github.com/rgonzalezabreu/masterpiece/blob/main/CODE_OF_CONDUCT.md
done

2022-05-03 08:12 UTC, mdelgadodiaz83-erni approved these changes

2022-05-04 07:48 UTC, Rabosa616 approved these changes

2022-05-04 07:48 UTC, merged